fixtures:
  symlinks:
    service_example: "#{source_dir}"
  repositories:
    registry:
      repo: 'https://github.com/puppetlabs/puppetlabs-registry.git'
      ref: '1.0.3'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.5.1'
